const constants = require('generator-jhipster/generators/generator-constants');

const { SERVER_MAIN_RES_DIR, SERVER_MAIN_SRC_DIR, SERVER_TEST_SRC_DIR } = constants;

const expectedFiles = {
  microservices: [`${SERVER_MAIN_RES_DIR}static/favicon.png`],
  server: [
    'bundle/descriptor.yaml',
    'prepareMicrofrontends.sh',
    'prepareBundle.sh',
    'prepareDockerImage.sh',
    'buildBundle.sh',
    `${SERVER_MAIN_SRC_DIR}com/mycompany/myapp/config/SpringFoxConfiguration.java`,
  ],
  entity: {
    server: {
      common: [`${SERVER_MAIN_SRC_DIR}com/mycompany/myapp/web/rest/schema/FooSchemaResource.java`],
      noDb: [
        `${SERVER_MAIN_SRC_DIR}com/mycompany/myapp/domain/Foo.java`,
        `${SERVER_MAIN_SRC_DIR}com/mycompany/myapp/repository/FooRepository.java`,
        `${SERVER_MAIN_SRC_DIR}com/mycompany/myapp/repository/impl/FooRepositoryImpl.java`,
        `${SERVER_MAIN_SRC_DIR}com/mycompany/myapp/web/rest/FooResource.java`,
        `${SERVER_TEST_SRC_DIR}com/mycompany/myapp/domain/FooTest.java`,
        `${SERVER_TEST_SRC_DIR}com/mycompany/myapp/web/rest/FooResourceIT.java`,
      ],
      serviceClass: [`${SERVER_MAIN_SRC_DIR}com/mycompany/myapp/service/FooService.java`],
      serviceImpl: [`${SERVER_MAIN_SRC_DIR}com/mycompany/myapp/service/impl/FooServiceImpl.java`],
    },
    widget: {
      detailsWidget: [
        'ui/widgets/foo/detailsWidget/bundle/foo-details-widget.ftl',
        'ui/widgets/foo/detailsWidget/bundle/foo-details-widget-descriptor.yaml',
        'ui/widgets/foo/detailsWidget/public/favicon.ico',
        'ui/widgets/foo/detailsWidget/public/index.html',
        'ui/widgets/foo/detailsWidget/public/robots.txt',
        'ui/widgets/foo/detailsWidget/scripts/i18next-scanner.config.js',
        'ui/widgets/foo/detailsWidget/src/api/foo.js',
        'ui/widgets/foo/detailsWidget/src/api/helpers.js',
        'ui/widgets/foo/detailsWidget/src/auth/KeycloakContext.js',
        'ui/widgets/foo/detailsWidget/src/auth/KeycloakViews.js',
        'ui/widgets/foo/detailsWidget/src/auth/withKeycloak.js',
        'ui/widgets/foo/detailsWidget/src/components/__mocks__/fooMocks.js',
        'ui/widgets/foo/detailsWidget/src/components/__mocks__/i18n.js',
        'ui/widgets/foo/detailsWidget/src/components/__tests__/FooDetails.test.js',
        'ui/widgets/foo/detailsWidget/src/components/__tests__/FooDetailsContainer.test.js',
        'ui/widgets/foo/detailsWidget/src/components/__types__/foo.js',
        'ui/widgets/foo/detailsWidget/src/components/__types__/keycloak.js',
        'ui/widgets/foo/detailsWidget/src/components/__types__/ref.js',
        'ui/widgets/foo/detailsWidget/src/components/common/Notification.js',
        'ui/widgets/foo/detailsWidget/src/components/foo-field-table/FooFieldTable.js',
        'ui/widgets/foo/detailsWidget/src/components/FooDetails.js',
        'ui/widgets/foo/detailsWidget/src/components/FooDetailsContainer.js',
        'ui/widgets/foo/detailsWidget/src/custom-elements/FooDetailsElement.js',
        'ui/widgets/foo/detailsWidget/src/custom-elements/widgetEventTypes.js',
        'ui/widgets/foo/detailsWidget/src/helpers/widgetEvents.js',
        'ui/widgets/foo/detailsWidget/src/i18n/locales/en.json',
        'ui/widgets/foo/detailsWidget/src/i18n/locales/index.js',
        'ui/widgets/foo/detailsWidget/src/i18n/locales/it.json',
        'ui/widgets/foo/detailsWidget/src/i18n/constants.js',
        'ui/widgets/foo/detailsWidget/src/i18n/i18n.js',
        'ui/widgets/foo/detailsWidget/src/i18n/setLocale.js',
        'ui/widgets/foo/detailsWidget/src/index.css',
        'ui/widgets/foo/detailsWidget/src/index.js',
        'ui/widgets/foo/detailsWidget/.env.local',
        'ui/widgets/foo/detailsWidget/.env.production',
        'ui/widgets/foo/detailsWidget/jsconfig.json',
        'ui/widgets/foo/detailsWidget/LICENSE',
        'ui/widgets/foo/detailsWidget/package.json',
        'ui/widgets/foo/detailsWidget/package-lock.json',
        'ui/widgets/foo/detailsWidget/README.md',
      ],
    },
  },
};

module.exports = expectedFiles;
