name: Generator
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - '*'
jobs:
  generator-jhipster-entando:
    name: npm-test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.15.0'
      - run: npm ci
      - run: npm link
      - run: npm run test
