name: Internal Snapshot Publication

on:
  push:
    tags:
      - 'v*'

env:
  ENTANDO_OPT_USE_PPL_TAG: "v1.1.0"
  ENTANDO_OPT_FEATURES: "${{ secrets.ENTANDO_OPT_FEATURES }}"
  ENTANDO_OPT_GLOBAL_FEATURES: "${{ secrets.ENTANDO_OPT_GLOBAL_FEATURES }}"
  ENTANDO_OPT_LOG_LEVEL: "${{ secrets.ENTANDO_OPT_LOG_LEVEL }}"
  ENTANDO_OPT_REPO_BOM_URL: "${{ secrets.ENTANDO_OPT_REPO_BOM_URL }}"
  PPL_CONTEXT: ${{ toJson(github) }}
  GIT_USER_NAME: "${{ secrets.GIT_USER_NAME }}"
  GIT_USER_EMAIL: "${{ secrets.GIT_USER_EMAIL }}"
  LOCAL_CLONE_DIR: "local-checkout"


jobs:
  internal-publication:
    runs-on: ubuntu-latest
    steps:
      - name: "PR PIPELINE START"
        id: START
        run: |
          ${{ secrets.ENTANDO_OPT_PPL_INSTALL_CMD }}
          ~/ppl-run status-report \
            .. @setup-feature-flags "PR_FORMAT_CHECK" "BOM_CHECK" "BOM" \
            .. @setup-features-list "SCAN_MATRIX" true SONAR_SCAN OWASP_SCAN SNYK_SCAN \
          ;
      #~ CHECKOUT
      - name: "Checkout"
        run: |
          ~/ppl-run checkout-branch base \
            --id "CHECKOUT FOR NEXUS PUBLICATION" \
            --lcd "$LOCAL_CLONE_DIR" \
          ;
      #~ NODE
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      #~ NPM CACHE
      - name: "Cache NPM Packages"
        id: package-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm
      #~ BUILD CACHE
      - name: "Cache Build Dir"
        id: build-cache
        uses: actions/cache@v2
        with:
          path:  "${{ env.LOCAL_CLONE_DIR }}/build/"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #~ PUBLISH PACKAGE
      - name: "Publish package"
        run: |
          ~/ppl-run generic PUBLISH \
            --id "PUBLICATION" \
            --lcd "$LOCAL_CLONE_DIR"
      #~ PUBLISH TO DOCKER IMAGE
      - name: "Publish docker"
        env:
          ENTANDO_OPT_DOCKER_BUILDS: "${{ secrets.ENTANDO_OPT_DOCKER_BUILDS }}"
          ENTANDO_OPT_DOCKER_ORG: "${{ secrets.ENTANDO_OPT_DOCKER_ORG }}"
          ENTANDO_OPT_DOCKER_USERNAME: "${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}"
          ENTANDO_OPT_DOCKER_PASSWORD: "${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}"
        run: |
          ~/ppl-run docker publish "$ENTANDO_OPT_DOCKER_BUILDS"\
            --id "PUBLISH-DOCKER" \
            --lcd "$LOCAL_CLONE_DIR"
